language: python
python:
  - 3.6

services:
  - postgresql: "9.6"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'postgres';" -U postgres

install: pip install -r requirements.txt

script: pytest