language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

install: pip install -r requirements.txt

script: pytest