language: python
python:
  - 3.6

services:
  - postgresql: "9.6"

before_script:
  - psql -c 'create database addmoretest;' -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'mat610';" -U postgres

install: pip install -r requirements.txt

script:
  - coverage run --source=resources,Model,app -m pytest 
  - coverage report

after-success:
  - codeclimate-test-reporter